Metrics/LineLength:
  Exclude:
    - '*.gemspec'

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
